## 2. Data Description and Visualization

In this phase, provide an overview of the distribution of the outcome variables and select a
few key features for visualization. Present these insights using graphical representations
and a summary table of measures. You can refer to the RandomForestDemo notebook for
inspiration.

Additionally, a starter notebook is provided where a visual representation of the biomes
(Biome_obs) are showed on a global map.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split, KFold, cross_val_score, GridSearchCV
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import ConfusionMatrixDisplay, accuracy_score, classification_report
#from ISLP import load_data # Not needed
import shap
import seaborn as sns

/Users/andrearaaschou/courses/BERN01/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
#LPJ-GUESS output
lpj_output = pd.read_csv("./../data/LPJ-GUESS_output_BERN1.csv")
lpj_output.head()

,Lon,Lat,NPP,SoilR,MaxBiomeCmax,MaxBiomeLAI,VegC,LitterC,SoilC,Biome_Cmax,Biome_LAI,Biome_obs
0,39.75,-1.25,0.429,0.390,0.449,1.9821,1.225,0.758,5.941,8,12,12
1,150.25,-34.25,0.554,0.451,6.883,3.3174,6.953,3.221,10.566,7,7,6
2,-63.75,82.75,0.000,0.000,0.000,0.0000,0.000,0.003,0.002,13,13,17
3,59.25,30.75,0.043,0.042,0.090,0.2146,0.127,0.084,0.543,7,11,14
4,24.25,27.75,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,13,13,17

In [10]:
# Grid information
grid_df = pd.read_csv("./../data/gridlist_pan_gfed_ISO3_UN_ecoregion.txt",sep=" ")
grid_df.head()

     Lon    Lat  GFED-region  Pan_2007 ISO3   UN  Ecoregion
0 -69.75 -55.25            5  Americas  CHL  152          4
1 -69.25 -55.25            5  Americas  CHL  152          4
2 -71.25 -54.75            5  Americas  CHL  152          4
3 -70.75 -54.75            5  Americas  CHL  152          4
4 -70.25 -54.75            5  Americas  CHL  152          4

In [8]:
# Soil texture
soil_df = pd.read_csv("./../data/soilmap.dat",sep="\t")
soil_df.head()

       lon    lat  clay  silt  sand   orgC    CN   pH  cellfraction
0  -179.75  71.25  0.08  0.37  0.55  0.020  11.0  5.9         0.482
1  -179.75  68.75  0.20  0.48  0.32  0.031  17.0  6.3         0.753
2  -179.75  68.25  0.20  0.48  0.32  0.031  17.0  6.3         0.447
3  -179.75  67.75  0.20  0.48  0.32  0.031  17.0  6.3         0.526
4  -179.75  67.25  0.20  0.48  0.32  0.031  17.0  6.3         0.422

## 3. Binary classification

In this part, you are going to build a binary classifier to classify two classes of biomes from
“Biome_obs”. You can choose one of the biomes and try to train a classifier that can distinguish this biome from the other data, e.g, ’Arctic/alpine tundra’ or ’not Arctic/alpine tundra’.

One way to narrow down the data if you have trouble creating the binary classifier is to
only include samples from two different country codes or regions

### 3.1. Data split

Split your dataset into two parts: a training set and a test set. The training set is used to
train the model, and the test set is used to evaluate model performance. Think through
how you split your data and what fits your purpose. Ways to split your data could be
through climate, zone, biome, countries or continents. Are all the biomes represented in
both your train and test data? Are the frequency of biome classes representative?

### 3.2. Model training
Next, train a Random Forest binary classification model. You can start by using training
data from one smaller region (could be one country code). Evaluate your model and try to
optimise the hyperparameters.

### 3.3. Model evaluation
Evaluate the model's performance using appropriate metrics for binary classification. Common metrics include precision, recall, and to plot the predictions in a confusion matrix. Test the model trained on one part of the world on the same biome in another part of the world,
e.g., Arctic/alpine tundra in either North America or Siberia. Does the model show equal 
skill in both areas? Could the features you have chosen affect the skill of the model in another part of the world? Why?

### 3.4. Feature importance and model interpretation
Analyze which features played the most crucial role in your model's decisions. Finally, discuss and interpret your results comprehensively, and explore any misclassifications to gain valuable insights into how well machine learning models adapt to different continents and
environments. Are all features that you used for training necessary? Could you reduce the
number of features used? Were there features that you did not use that could be important? Why would they be important?
Optional: Plot the misclassified regions on a world map.